### ISSUE TITLE
change the directory of the fig files

### ISSUE THREAD

**Issue by erfanhamdi** [erfanhamdi/beamer_template#1]
As I used a specific version of osloMet beamer template. 
the names remain what they were in the first implementation, it would be a good idea to change them and the corresponding latex code

**Comment by NevilleMthw** [comment]
Hi, is the ```.fig``` files present in the repository or is it something related in the code?

**Comment by erfanhamdi** [comment]
> Hi, is the `.fig` files present in the repository or is it something related in the code?

oh sorry I wasn't clear, by fig files I meant the directory named `OM-images` get changed to  something like `figs` and then again the references in the code needs to be changed
