### ISSUE TITLE
change the name of theme styles and classes

### ISSUE THREAD

**Issue by erfanhamdi** [erfanhamdi/beamer_template#2]
Change the names of the styles and classes so that it represents SUT

**Comment by NevilleMthw** [comment]
Hi, could you provide an example of what should be changed?

**Comment by erfanhamdi** [comment]
Hi Matthew

I meant the files like `beamercolorthemeoslomet.sty` and all their references to something like `beamercolorthemesut.sty`

> Hi, could you provide an example of what should be changed?

**Comment by NevilleMthw** [comment]
Oh alright, I thought maybe regarding the ```.tex``` file. I could do this issue, if no one has occupied it.

**Comment by erfanhamdi** [comment]
> Oh alright, I thought maybe regarding the `.tex` file. I could do this issue, if no one has occupied it.

That would be great!
