### ISSUE TITLE
Change the content of the presentation to Template text and figures

### ISSUE THREAD

**Issue by erfanhamdi** [erfanhamdi/beamer_template#3]
As you can see it is a part of my own presentation, It would be better to change the text and the figures to some Stock text and images

**Comment by NevilleMthw** [comment]
Hi @erfanhamdi,

Just to be clear, you want to change all the current text and images to stock text and images?

Regards,
Neville

**Comment by erfanhamdi** [comment]
Hi Neville

Yeah exactly.
Thanks!

**Comment by erfanhamdi** [comment]
just keep the logos and the cover watermark

**Comment by NevilleMthw** [comment]
Alright, I'll get it done.

**Comment by erfanhamdi** [comment]
Great!
